export interface DashboardRecord {
  srNo: number;
  shgName: string;
  videoName: string;
  videoUrl: string;
  dateCreated: string;
  subjectFromAI?: string;
  output: string;
  engagement: number;
  engagementComments: string;
  classIssues: number;
  classIssuesComments: string;
  instructorIssues: number;
  instructorIssuesComments: string;
  contentStructure: number;
  contentStructureComments: string;
  platformUsage: number;
  platformUsageComments: string;
  finalScore: number;
  issuesToImprove: string;
}

export const dashboardData: DashboardRecord[] = [
  {
    srNo: 1,
    shgName: "SHG TC PURZAGIR (02:19:01)",
    videoName: "Computer_AI(25-07-2025).mp4",
    videoUrl: "https://drive.google.com/drive/folders/1h7e6li2mB9IsblOc8ASdglqHXlayQjY1",
    dateCreated: "2025-07-25",
    output: "Video from the classroom was dark for the entire session. AI conducted the rest of the audit properly, but since the room was dark in the entire session the students were not visible",
    engagement: 15,
    engagementComments: "Actively asked questions to engage students, though the technical issues hampered interaction",
    classIssues: 2,
    classIssuesComments: "Video from the classroom was dark for the entire session.",
    instructorIssues: 15,
    instructorIssuesComments: "Did not state the learning objectives at the beginning of the session. Could have used more interactive platform tools like polls to check for understanding",
    contentStructure: 18,
    contentStructureComments: "The content was logically structured, starting with basic concepts and moving to practical examples using ChatGPT, Google AI studio.",
    platformUsage: 10,
    platformUsageComments: "Effectively used screen sharing, but other tools like polls were not utilized.",
    finalScore: 60,
    issuesToImprove: "Clear learning objectives, dark room lighting"
  },
  {
    srNo: 2,
    shgName: "SHG TC PURZAGIR (02:19:01)",
    videoName: "Computer_internet email(01-08-2025).mp4",
    videoUrl: "https://drive.google.com/file/d/17hM7qUTUuyDUXxb0QAuTiy_Vpnn4hA8s/view?usp=drive_link",
    dateCreated: "2025-08-01",
    output: "AI conducted the audit but power outrage happened at the end",
    engagement: 10,
    engagementComments: "The instructor made several attempts to engage the students by asking direct questions, but the class remained largely unresponsive and had to be prompted for every answer.",
    classIssues: 2,
    classIssuesComments: "The session was cut short due to a power failure at the class's location. The classroom was very dark, the video feed was frequently paused due to network issues, and they joined the session late.",
    instructorIssues: 14,
    instructorIssuesComments: "The instructor did not introduce herself by name. She spent a significant portion of the session reading learning objectives from a document rather than engaging in dynamic instruction and could have used more interactive methods.",
    contentStructure: 15,
    contentStructureComments: "A PDF document with clear learning objectives was used to structure the session, and the flow followed the points on the presentation.",
    platformUsage: 14,
    platformUsageComments: "The instructor effectively used screen sharing to present the session material, but no other interactive tools were used.",
    finalScore: 72,
    issuesToImprove: "Instructor relied heavily on reading from a prepared document, power cut issue"
  },
  {
    srNo: 3,
    shgName: "SHG TC PURZAGIR (02:19:01)",
    videoName: "Math_IntegerPositive(06-08-2025).mp4",
    videoUrl: "https://drive.google.com/file/d/18X7UVRNRzuk2AYJqhvvLjpG_BnHdQDcu/view?usp=drive_link",
    dateCreated: "2025-08-06",
    output: "AI conducted the rest of the audit properly, but the session was severly interrupted taken over by another staff member for english tenses",
    engagement: 19,
    engagementComments: "Excellent engagement. The instructor constantly asked questions, checked for understanding, and involved students by name, leading to active and unscripted responses",
    classIssues: 2,
    classIssuesComments: "The session was severely disrupted. Part 2 was abruptly interrupted by another staff member and taken over by a different instructor teaching an unrelated subject. This was a fatal error for the session's continuity.",
    instructorIssues: 18,
    instructorIssuesComments: "The instructor's performance was strong. The original instructor finished the topic in 43 minutes instead of 1 hour as interrupted mid-session.",
    contentStructure: 18,
    contentStructureComments: "The content was logically structured, starting with foundational concepts of integers and progressing to their properties (Closure, Commutative, Associative).",
    platformUsage: 19,
    platformUsageComments: "Optimal use of platform tools, including screen sharing for slides and a digital pen/whiteboard to illustrate concepts and solve problems live.",
    finalScore: 78,
    issuesToImprove: "Session was completely derailed by poor on-site coordination, multiple students speak at a time"
  },
  {
    srNo: 4,
    shgName: "SHG TC PURZAGIR (02:19:01)",
    videoName: "Computer_Email Internet(08-08-2025).mp4",
    videoUrl: "https://drive.google.com/file/d/1QSabK4YPceC_CARGTBKIsfacPhtXxPnu/view?usp=drive_link",
    dateCreated: "2025-08-08",
    output: "AI conducted the rest of the audit properly, but the session was severly interrupted due to internet issue from Instructor's end",
    engagement: 5,
    engagementComments: "The instructor tried to engage students, but the interaction was poor and seemed coached by an off-screen person.",
    classIssues: 8,
    classIssuesComments: "Student participation was heavily prompted, making it feel artificial. Students were also talking amongst themselves while the instructor was speaking.",
    instructorIssues: 13,
    instructorIssuesComments: "The instructor was frequently disconnected from the call and once for nearly three minutes.",
    contentStructure: 15,
    contentStructureComments: "The content was logical, explaining email components before a practical demonstration.",
    platformUsage: 16,
    platformUsageComments: "Effectively used screen sharing for a PDF presentation and a live Gmail demonstration.",
    finalScore: 57,
    issuesToImprove: "Instructor was getting internet issue and getting disconnected from a call frequently"
  },
  {
    srNo: 5,
    shgName: "SHG TC PURZAGIR (02:19:01)",
    videoName: "Math_Integer(13-08-2025).mp4",
    videoUrl: "https://drive.google.com/file/d/1PyAFs4qI-z4O0UScEJB4ZS5B2b0cQnN5/view?usp=drive_link",
    dateCreated: "2025-08-13",
    output: "AI conducted the audit properly",
    engagement: 14,
    engagementComments: "The instructor effectively engaged the students by frequently asking questions and encouraging participation, resulting in a genuine and interactive learning environment.",
    classIssues: 12,
    classIssuesComments: "While engagement was good, some students struggled with prerequisite concepts, which required the instructor to spend additional time on review. Minor background noise was present.",
    instructorIssues: 18,
    instructorIssuesComments: "The instructor did not provide a formal self-introduction or outline the learning objectives at the beginning of the session",
    contentStructure: 16,
    contentStructureComments: "The content was presented in a logical and well-organized manner, starting with a clear agenda on the whiteboard before moving to the presentation slides.",
    platformUsage: 16,
    platformUsageComments: "The instructor made optimal use of platform tools, effectively using both a digital whiteboard for outlining topics and screen sharing for the main presentation.",
    finalScore: 76,
    issuesToImprove: "Some participants required reinforcement of basic concepts from the previous class, suggesting a need for a quick review"
  },
  {
    srNo: 6,
    shgName: "SHG TC PURZAGIR (02:19:01)",
    videoName: "Computer_Hardware class(16-08-2025).mp4",
    videoUrl: "https://drive.google.com/file/d/1lNB-Gsq6PwVOM25UafPGYfKcLOlxG0kC/view?usp=drive_link",
    dateCreated: "2025-08-16",
    output: "AI conducted the audit properly",
    engagement: 10,
    engagementComments: "The instructor consistently attempted to engage students with questions, but the class was largely passive and required direct prompting to respond.",
    classIssues: 15,
    classIssuesComments: "The participants were generally passive, often responding in unison, which made it difficult to assess individual understanding.",
    instructorIssues: 14,
    instructorIssuesComments: "The instructor did not provide a formal introduction or outline the session's agenda. A persistent echo was present in the instructor's audio.",
    contentStructure: 18,
    contentStructureComments: "The lesson was well-structured, starting with a video and followed by a detailed explanation with relatable analogies.",
    platformUsage: 9,
    platformUsageComments: "The instructor made optimal use of the platform by effectively using screen sharing for a video and a PDF document.",
    finalScore: 77,
    issuesToImprove: "Strategies to encourage individual participation should be explored to avoid chorus responses, Echo sound throughout the session from classroom"
  },
  {
    srNo: 7,
    shgName: "SHG TC PURZAGIR (02:19:01)",
    videoName: "Math Integer Multiplication(20-08-2025)3.mp4",
    videoUrl: "https://drive.google.com/file/d/1lYbPDjj43sQH1rvF-_zU9L08bjObFbnz/view?usp=drive_link",
    dateCreated: "2025-08-20",
    output: "AI conducted the audit properly, instructor briefly disconnected for 19 seconds",
    engagement: 20,
    engagementComments: "Participant engagement was good. Students responded promptly, actively participated by raising their hands, and demonstrated a genuine understanding of the topic without off-screen prompting.",
    classIssues: 17,
    classIssuesComments: "Minor issues included the need for class's initial camera adjustments for a clear view, slight background noise from the classroom, and students sometimes answering in chorus",
    instructorIssues: 18,
    instructorIssuesComments: "The instructor experienced a brief disconnection of about 19 seconds and occasionally spoke over students while they were answering.",
    contentStructure: 19,
    contentStructureComments: "The lesson was well-structured, moving logically from a recap of previous topics to new concepts, which were then reinforced with examples and worksheets.",
    platformUsage: 19,
    platformUsageComments: "The instructor made optimal use of the platform by effectively using screen sharing and annotation tools to solve problems live with the class.",
    finalScore: 93,
    issuesToImprove: "Class camera setup, and audio echo slightly impacted the session"
  },
  {
    srNo: 8,
    shgName: "SHG TC PURZAGIR (02:19:01)",
    videoName: "Computer languages(22-08-2025).mp4",
    videoUrl: "https://drive.google.com/file/d/1bQkqhlM4Mtv6X4PG3uVCt3EPU4Ksz3mv/view?usp=drive_link",
    dateCreated: "2025-08-22",
    output: "AI conducted the audit properly, instructor side audio echoed initially",
    engagement: 17,
    engagementComments: "The instructor actively engaged students with direct questions and relatable analogies, resulting in good participation from the class.",
    classIssues: 18,
    classIssuesComments: "The classroom environment was well-managed with attentive students and no significant disruptions or technical problems from their end.",
    instructorIssues: 14,
    instructorIssuesComments: "The instructor's audio quality was poor with a noticeable echo. Could have used more interactive platform tools like polls to check for understanding.",
    contentStructure: 18,
    contentStructureComments: "The content was logically structured, progressing from machine and assembly language to high-level languages and their respective translators.",
    platformUsage: 20,
    platformUsageComments: "Effectively used screen sharing to present notes and diagrams, multiple-choice questions to check the understanding of the students well utilized.",
    finalScore: 87,
    issuesToImprove: "The instructor need to pre check the audio echo issue, class camera adjustment should be done prior to the class"
  },
  {
    srNo: 9,
    shgName: "SHG TC PURZAGIR (02:19:01)",
    videoName: "Maths_fraction(27-08-2025).mp4",
    videoUrl: "https://drive.google.com/file/d/1N0KM2ofwBP4IAygZ3GOIqhQyRV0yJU6d/view?usp=drive_link",
    dateCreated: "2025-08-27",
    output: "AI conducted the audit properly, but students visibility was poor because of power outrage in entire session",
    engagement: 18,
    engagementComments: "Excellent and consistent engagement. The instructor used direct questions and sought confirmation to ensure students were actively participating and understanding the material.",
    classIssues: 4,
    classIssuesComments: "A power outage at the student location caused severe visibility issues for the entire session. Additionally, audio from one student group was distant and had an echo.",
    instructorIssues: 18,
    instructorIssuesComments: "Minor issues noted: the instructor initially referred to a screen students couldn't see, and one explanation was briefly unclear before being corrected.",
    contentStructure: 19,
    contentStructureComments: "The content was logically structured, progressing from foundational concepts like integer division to more complex problems involving fractions, with clear transitions.",
    platformUsage: 20,
    platformUsageComments: "Optimal and highly effective use of screen sharing, prepared PDFs, and annotation tools to demonstrate mathematical steps visually.",
    finalScore: 79,
    issuesToImprove: "Students dark session, Echo audio from background, Unison answering of students difficult to understand individual responses, Brief disconnection from instructor"
  },
  {
    srNo: 10,
    shgName: "SHG TC PURZAGIR (02:19:01)",
    videoName: "Computer_word(29-08-2025).mp4",
    videoUrl: "https://drive.google.com/file/d/1jkTEigs7VGCbeacwrE9yJOBGNGdzKflO/view?usp=drive_link",
    dateCreated: "2025-08-29",
    output: "AI conducted the audit properly, but initially audio and later students visibility was poor because of power outrage in entire session",
    engagement: 16,
    engagementComments: "Engagement was impossible initially due to technical failure at client/student's side, but excellent in the other sessions where the instructor used a call-and-response method effectively.",
    classIssues: 2,
    classIssuesComments: "A fatal audio failure from the classroom prevented the first part of the session from starting. The video feed was also too dark to see participants.",
    instructorIssues: 16,
    instructorIssuesComments: "The instructor was unable to troubleshoot the initial technical issues. A formal introduction was provided.",
    contentStructure: 17,
    contentStructureComments: "When delivered, the content was logically structured, moving from presentation slides to live software demonstration. No content could be delivered in the beginning.",
    platformUsage: 16,
    platformUsageComments: "Effectively used screen sharing for demonstrations in two sessions, but could not overcome the technical issues initially.",
    finalScore: 67,
    issuesToImprove: "The classroom's technical setup (audio and lighting) was poor"
  },
  {
    srNo: 11,
    shgName: "SHG TC PURZAGIR (02:19:01)",
    videoName: "math pattern(3-9-2025).mp4",
    videoUrl: "https://drive.google.com/file/d/1LwTVAVvpZ_hMVwUfM9PRu8q2igAt7dv6/view?usp=drive_link",
    dateCreated: "2025-09-03",
    output: "",
    engagement: 18,
    engagementComments: "Excellent engagement was achieved through direct questioning and interactive exercises, resulting in quick and clear student responses",
    classIssues: 18,
    classIssuesComments: "The class was well-behaved and actively participated once the session began. No issues were observed from the participants' side.",
    instructorIssues: 14,
    instructorIssuesComments: "",
    contentStructure: 18,
    contentStructureComments: "",
    platformUsage: 17,
    platformUsageComments: "",
    finalScore: 85,
    issuesToImprove: "Freezing of video from both ends impacted the engagement mid sessions highlighting the need for pre-session technical checks. The initial 2 minutes and 3 seconds were lost due to the technical problem, impacting the flow of the lesson."
  },
  {
    srNo: 12,
    shgName: "SHG TC PURZAGIR (02:19:01)",
    videoName: "Computer Files_folders(06-09-2025).mp4",
    videoUrl: "https://drive.google.com/file/d/1nnsF8NsGtbjGa07uJIaVXOt90PoVqOdn/view?usp=drive_link",
    dateCreated: "2025-09-06",
    output: "",
    engagement: 18,
    engagementComments: "A key strength; the instructor demonstrated excellent use of questions and interactive elements which kept the students actively involved in discussions and Q&A segments.",
    classIssues: 14,
    classIssuesComments: "The class was generally well-behaved, though there were minor instances of students talking over each other.",
    instructorIssues: 16,
    instructorIssuesComments: "The instructor provided an incomplete introduction at the start of the session. A minor technical issue with an audio echo was also noted.",
    contentStructure: 20,
    contentStructureComments: "The lesson on computer files and folders was logically structured and progressed in a clear and organized manner, making it easy for students to follow.",
    platformUsage: 18,
    platformUsageComments: "The instructor made optimal and effective use of platform tools, primarily utilizing screen sharing for instructional materials",
    finalScore: 87,
    issuesToImprove: "Minor audio issues (echo) should be resolved before the session. Ensure a quiet environment with no students talking over one another."
  },
  {
    srNo: 13,
    shgName: "SHG TC BIRDHA (23:21:02)",
    videoName: "SHG TC BIRDHA SR Maths(10-09-2025).mp4",
    videoUrl: "https://drive.google.com/file/d/1SLC7XnnIXa6DJBN3rQPEoffwd6q6KgHo/view?usp=drive_link",
    dateCreated: "2025-09-10",
    output: "",
    engagement: 15,
    engagementComments: "Engagement was high, with students responding energetically to the instructor's questions. However, the quality is rated as \"Dummy\" because an on-site moderator frequently prompted the students for choral answers, making individual comprehension difficult to assess.",
    classIssues: 12,
    classIssuesComments: "The classroom had a minor technical issue with a flickering light. The primary issue was the constant prompting of students by the on-site moderator, which made the interaction feel coached rather than spontaneous.",
    instructorIssues: 18,
    instructorIssuesComments: "The instructor provided a clear introduction and maintained a professional demeanor. She managed the class well despite the coached responses and used positive reinforcement effectively.",
    contentStructure: 18,
    contentStructureComments: "The content was logically structured, starting with a basic definition of integers and progressing to operations and rules for signs. The use of real-world examples aided understanding.",
    platformUsage: 19,
    platformUsageComments: "The instructor made optimal use of the platform's features, seamlessly switching between a slide presentation and a digital whiteboard for explanations and live problem-solving.",
    finalScore: 82,
    issuesToImprove: "The engagement from the students appeared heavily coached by the on-site moderator, with frequent prompts to answer loudly and in unison. The reliance on choral responses makes it difficult to gauge the understanding of individual students. A flickering light in the classroom was a minor distraction."
  },
  {
    srNo: 14,
    shgName: "SHG TC PURZAGIR (02:19:01)",
    videoName: "SHG TC PURZAGIR Maths(10-09-2025).mp4",
    videoUrl: "https://drive.google.com/file/d/10dmZWoauyJuggkEhOHPSSyfLeutN_0Wt/view?usp=drive_link",
    dateCreated: "2025-09-10",
    output: "",
    engagement: 20,
    engagementComments: "The participants were actively engaged throughout the session, responding to questions, attempting to solve problems, and asking for clarification when needed. The instructor fostered a positive and interactive learning environment.",
    classIssues: 20,
    classIssuesComments: "No significant class-related issues were observed during this session, with only a brief screen blackout of 5 seconds noted.",
    instructorIssues: 20,
    instructorIssuesComments: "No instructor-related issues were noted during the session. The instructor was well-prepared and managed the class effectively.",
    contentStructure: 20,
    contentStructureComments: "The content was well-structured, starting with foundational concepts and progressing to more complex patterns. Visual aids were effectively integrated with explanations.",
    platformUsage: 20,
    platformUsageComments: "The instructor effectively used the digital whiteboard and presentation slides to illustrate concepts and solve problems collaboratively with students, demonstrating optimal platform usage.",
    finalScore: 100,
    issuesToImprove: "No significant issues to improve were observed in this session."
  },
  {
    srNo: 15,
    shgName: "SHG TC SR.NEW BIDUPUR (35:18:02)",
    videoName: "SHG TC VIDUPUR Maths(10-09-2025).mp4",
    videoUrl: "https://drive.google.com/file/d/1T438r8f8LRqEGbEnWzQGvhu-JakPbCnz/view?usp=drive_link",
    dateCreated: "2025-09-10",
    output: "",
    engagement: 16,
    engagementComments: "",
    classIssues: 17,
    classIssuesComments: "",
    instructorIssues: 19,
    instructorIssuesComments: "",
    contentStructure: 18,
    contentStructureComments: "",
    platformUsage: 18,
    platformUsageComments: "",
    finalScore: 88,
    issuesToImprove: "Most side of the participants kept their cameras off, making it difficult to gauge non-verbal cues and individual engagement visually. Polls or similar interactive tools were underutilized for knowledge checks during the session."
  },
  {
    srNo: 16,
    shgName: "SHG TC BHUSRA (21:15:02)",
    videoName: "SHG TC BHUSRA (21:15:02) - 2025/09/10 17:26 GMT+05:30 – Recording",
    videoUrl: "NA",
    dateCreated: "2025-09-10",
    output: "NJ Teacher present 5:30 to 6:30 pm but class missed the session",
    engagement: 0,
    engagementComments: "NA",
    classIssues: 0,
    classIssuesComments: "NA",
    instructorIssues: 10,
    instructorIssuesComments: "No instructor-related issues were noted during the session.The instructor was professionally-dressed",
    contentStructure: 0,
    contentStructureComments: "NA",
    platformUsage: 5,
    platformUsageComments: "Optimal use of screen sharing, prepared PDFs for visual session.",
    finalScore: 15,
    issuesToImprove: ""
  },
  {
    srNo: 17,
    shgName: "SHG TC BHADSAR (07:20:03)",
    videoName: "SHG TC BHADSAR (07:20:03) - 2025/09/10 06:34 GMT+05:30 – Recording",
    videoUrl: "NA",
    dateCreated: "2025-09-10",
    output: "Ravikesh Teacher present, coordinated 4 to 5 pm but class missed the session due to no light",
    engagement: 0,
    engagementComments: "NA",
    classIssues: 0,
    classIssuesComments: "NA",
    instructorIssues: 10,
    instructorIssuesComments: "No instructor-related issues were noted during the session.The instructor was professionally-dressed",
    contentStructure: 0,
    contentStructureComments: "NA",
    platformUsage: 5,
    platformUsageComments: "Optimal use of screen sharing, prepared PDFs for visual session.",
    finalScore: 15,
    issuesToImprove: ""
  },
  {
    srNo: 18,
    shgName: "SHG TC PURZAGIR (02:19:01)",
    videoName: "SHG TC PURZAGIR Computer(12-09-2025).mp4",
    videoUrl: "https://drive.google.com/file/d/10jqGxDqxXP0x2TMbOytV8gK68PgMDO2i/view?usp=drive_link",
    dateCreated: "2025-09-12",
    output: "",
    engagement: 13,
    engagementComments: "",
    classIssues: 8,
    classIssuesComments: "",
    instructorIssues: 12,
    instructorIssuesComments: "",
    contentStructure: 14,
    contentStructureComments: "",
    platformUsage: 16,
    platformUsageComments: "",
    finalScore: 75,
    issuesToImprove: "shouting and collective answers from students, Instructor prompting for answers"
  },
  {
    srNo: 19,
    shgName: "SHG TC BIRDHA (23:21:02)",
    videoName: "SHG TC BIRDHA Computer(12-09-2025).mp4",
    videoUrl: "https://drive.google.com/file/d/1ovdsL_5eUeej1ADkJQcOv90KaS3dRvMY/view?usp=drive_link",
    dateCreated: "2025-09-12",
    output: "",
    engagement: 17,
    engagementComments: "",
    classIssues: 14,
    classIssuesComments: "",
    instructorIssues: 17,
    instructorIssuesComments: "",
    contentStructure: 19,
    contentStructureComments: "",
    platformUsage: 18,
    platformUsageComments: "",
    finalScore: 85,
    issuesToImprove: "The instructor might have over-explained very simple points, which could affect pacing for some learners. Occasional audio cuts. Flickering light in the classroom"
  },
  {
    srNo: 20,
    shgName: "SHG TC BHUSRA (21:15:02)",
    videoName: "SHG TC BHUSRA Computer(12-09-2025).mp4",
    videoUrl: "https://drive.google.com/file/d/1CI83wTO2vGMau15XPpS1m90hu4_Dafkt/view?usp=drive_link",
    dateCreated: "2025-09-12",
    output: "",
    engagement: 18,
    engagementComments: "The class demonstrated good engagement by actively responding to questions and participating in clapping at appropriate times, even when the instructor sometimes had difficulty hearing their answers. The instructor also actively engaged students with questions and encouragement.",
    classIssues: 5,
    classIssuesComments: "Audio clarity from the students' side was often unclear, making it difficult to understand responses and requiring repetitions. Additionally, the classroom was poorly lit, obstructing visibility, and the class was dismissed early due to a lack of content.",
    instructorIssues: 17,
    instructorIssuesComments: "The instructor received good scores for professional appearance and communication clarity. However, issues like lack of content leading to early dismissal affected the overall evaluation, despite effectively managing student audio challenges.",
    contentStructure: 13,
    contentStructureComments: "While the lesson had a clear, logical structure progressing from general concepts to specific examples, the overall lack of content led to an early dismissal of the class.",
    platformUsage: 16,
    platformUsageComments: "Optimal use of screen-sharing for the presentation was observed, alongside visible participant interaction.",
    finalScore: 69,
    issuesToImprove: "Poor audio and video clarity, Early dismissal of class"
  },
  {
    srNo: 21,
    shgName: "SHG TC BHADSAR (07:20:03)",
    videoName: "SHG TC BHADSAR (07:20:03) - 2025/09/12 16:07 GMT+05:30 – Recording",
    videoUrl: "NA",
    dateCreated: "2025-09-12",
    output: "Ravikesh Teacher present, coordinated 4 to 5 pm but class missed the session due to no light",
    engagement: 0,
    engagementComments: "NA",
    classIssues: 0,
    classIssuesComments: "NA",
    instructorIssues: 10,
    instructorIssuesComments: "No instructor-related issues were noted during the session.The instructor was professionally-dressed",
    contentStructure: 0,
    contentStructureComments: "NA",
    platformUsage: 5,
    platformUsageComments: "Optimal use of screen sharing, prepared PDFs for visual session.",
    finalScore: 15,
    issuesToImprove: ""
  },
  {
    srNo: 22,
    shgName: "SHG TC GORAKHPUR BRAMHPUR(13:05:04)",
    videoName: "SHG TC GORAKHPUR BRAMHPUR(13:05:04) - 2025/09/17 07:01 GMT+05:30 – Recording 2",
    videoUrl: "https://drive.google.com/file/d/13699hjnaP6zwf6fWsCnfsxGdrtxUSU-c/view?usp=drive_link",
    dateCreated: "2025-09-17",
    output: "",
    engagement: 19,
    engagementComments: "",
    classIssues: 16,
    classIssuesComments: "",
    instructorIssues: 17,
    instructorIssuesComments: "",
    contentStructure: 18,
    contentStructureComments: "",
    platformUsage: 18,
    platformUsageComments: "",
    finalScore: 88,
    issuesToImprove: "students could be encouraged to answer one at a time"
  },
  {
    srNo: 23,
    shgName: "SHG TC SAMASTIPUR BIDUPUR(35:18:02)",
    videoName: "SHG TC SAMASTIPUR BIDUPUR(35:18:02) - 2025/09/17 06:27 GMT+05:30 – Recording 2",
    videoUrl: "https://drive.google.com/file/d/1O7E8Isr5vKdT7NdTdKrjx2MBYwb84DJL/view?usp=drive_link",
    dateCreated: "2025-09-17",
    output: "",
    engagement: 5,
    engagementComments: "",
    classIssues: 4,
    classIssuesComments: "",
    instructorIssues: 18,
    instructorIssuesComments: "",
    contentStructure: 18,
    contentStructureComments: "",
    platformUsage: 18,
    platformUsageComments: "",
    finalScore: 63,
    issuesToImprove: "Critical Lack of Student Engagement, Classroom was noisy"
  },
  {
    srNo: 24,
    shgName: "SHG TC TIKAMGARH BIRDHA(23:21:02)",
    videoName: "SHG TC TIKAMGARH BIRDHA(23:21:02) - 2025/09/17 15:53 GMT+05:30 – Recording",
    videoUrl: "NA",
    dateCreated: "2025-09-17",
    output: "Ravikesh Teacher present, coordinated 4 to 5 pm but class missed the session due to no light",
    engagement: 0,
    engagementComments: "NA",
    classIssues: 0,
    classIssuesComments: "NA",
    instructorIssues: 10,
    instructorIssuesComments: "No instructor-related issues were noted during the session.The instructor was professionally-dressed",
    contentStructure: 0,
    contentStructureComments: "NA",
    platformUsage: 5,
    platformUsageComments: "Optimal use of screen sharing, prepared PDFs for visual session.",
    finalScore: 15,
    issuesToImprove: ""
  },
  {
    srNo: 25,
    shgName: "SHG TC MIRZAPUR PURZAGIR(02:19:01)",
    videoName: "SHG TC MIRZAPUR PURZAGIR(02:19:01) - 2025/09/17 15:58 GMT+05:30 – Recording",
    videoUrl: "https://drive.google.com/file/d/11eLbvNKGABFtW1b4tv22sDRRT8UnAWNw/view?usp=drive_link",
    dateCreated: "2025-09-17",
    output: "",
    engagement: 19,
    engagementComments: "",
    classIssues: 17,
    classIssuesComments: "",
    instructorIssues: 18,
    instructorIssuesComments: "",
    contentStructure: 18,
    contentStructureComments: "",
    platformUsage: 19,
    platformUsageComments: "",
    finalScore: 91,
    issuesToImprove: "minor technical glitches with the instructor's video feed"
  },
  {
    srNo: 26,
    shgName: "SHG TC MUZAFFARPUR BHUSRA(21:15:02)",
    videoName: "SHG TC MUZAFFARPUR BHUSRA(21:15:02) - 2025/09/17 16:06 GMT+05:30 – Recording 4",
    videoUrl: "https://drive.google.com/file/d/1Lx7oKWHBaMWfhAlAyJHlWWoM7G72feaS/view?usp=drive_link",
    dateCreated: "2025-09-17",
    output: "",
    engagement: 17,
    engagementComments: "",
    classIssues: 15,
    classIssuesComments: "",
    instructorIssues: 16,
    instructorIssuesComments: "",
    contentStructure: 15,
    contentStructureComments: "",
    platformUsage: 16,
    platformUsageComments: "",
    finalScore: 79,
    issuesToImprove: "critical screen-sharing, instructor's video feed froze momentarily"
  },
  {
    srNo: 27,
    shgName: "SHG TC BUXAR ITARAHI(06:10:02)",
    videoName: "SHG TC BUXAR ITARAHI(06:10:02)  - 2025/09/18 06:12 GMT+05:30 – Recording",
    videoUrl: "https://drive.google.com/file/d/155zVsAd4oko5S_nTbvdEd7NFa4x1j50c/view",
    dateCreated: "2025-09-18",
    output: "",
    engagement: 4,
    engagementComments: "",
    classIssues: 2,
    classIssuesComments: "",
    instructorIssues: 14,
    instructorIssuesComments: "",
    contentStructure: 15,
    contentStructureComments: "",
    platformUsage: 16,
    platformUsageComments: "",
    finalScore: 51,
    issuesToImprove: "Fatal Technical Error: The classroom's technical setup had a severe and persistent audio echo, which made it impossible for the instructor to hear or understand students"
  },
  {
    srNo: 28,
    shgName: "SHG TC MUZAFFARPUR BHUSRA(21:15:02)",
    videoName: "SHG TC MUZAFFARPUR BHUSRA(21:15:02) - 2025/09/18 06:17 GMT+05:30 – Recording 2",
    videoUrl: "https://drive.google.com/file/d/1JPDP_CU2iJMNOIeGseAoDGFPMc6rCDZc/view",
    dateCreated: "2025-09-18",
    output: "",
    engagement: 14,
    engagementComments: "",
    classIssues: 17,
    classIssuesComments: "",
    instructorIssues: 18,
    instructorIssuesComments: "",
    contentStructure: 18,
    contentStructureComments: "",
    platformUsage: 18,
    platformUsageComments: "",
    finalScore: 73,
    issuesToImprove: "Minor network connectivity issues caused brief interruptions and screen buffering. Students required prompting for answers"
  },
  {
    srNo: 29,
    shgName: "SHG TC AZAMGARH BHADSAR(07:20:03)",
    videoName: "SHG TC AZAMGARH BHADSAR(07:20:03) - 2025/09/18 16:44 GMT+05:30 – Recording",
    videoUrl: "https://drive.google.com/file/d/1jBjfxNKgh8QT2CT1Xx2sI4qtXRL00nd4/view",
    dateCreated: "2025-09-18",
    output: "",
    engagement: 18,
    engagementComments: "",
    classIssues: 17,
    classIssuesComments: "",
    instructorIssues: 19,
    instructorIssuesComments: "",
    contentStructure: 19,
    contentStructureComments: "",
    platformUsage: 19,
    platformUsageComments: "",
    finalScore: 92,
    issuesToImprove: "Students needed initial prompting from the on-site moderator to participate."
  },
  {
    srNo: 30,
    shgName: "SHG TC SAMASTIPUR BIDUPUR(35:18:02)",
    videoName: "SHG TC SAMASTIPUR BIDUPUR(35:18:02) - 2025/09/19 06:27 GMT+05:30 – Recording 2",
    videoUrl: "https://drive.google.com/file/d/1ZMI6v9A124yZbHp9BiDGu6KZ4sXZdsPp/view",
    dateCreated: "2025-09-19",
    output: "",
    engagement: 8,
    engagementComments: "",
    classIssues: 4,
    classIssuesComments: "",
    instructorIssues: 14,
    instructorIssuesComments: "",
    contentStructure: 15,
    contentStructureComments: "",
    platformUsage: 20,
    platformUsageComments: "",
    finalScore: 70,
    issuesToImprove: "Student participation was notably low, leading to monologues despite the instructor's efforts"
  },
  {
    srNo: 31,
    shgName: "SHG TC GORAKHPUR BRAMHPUR(13:05:04)",
    videoName: "SHG TC GORAKHPUR BRAMHPUR(13:05:04)  - 2025/09/19 06:02 GMT+05:30 – Recording",
    videoUrl: "NA",
    dateCreated: "2025-09-19",
    output: "NJ",
    engagement: 0,
    engagementComments: "NA",
    classIssues: 0,
    classIssuesComments: "NA",
    instructorIssues: 10,
    instructorIssuesComments: "No instructor-related issues were noted during the session.The instructor was professionally-dressed",
    contentStructure: 0,
    contentStructureComments: "NA",
    platformUsage: 5,
    platformUsageComments: "Optimal use of screen sharing, prepared PDFs for visual session.",
    finalScore: 15,
    issuesToImprove: ""
  },
  {
    srNo: 32,
    shgName: "SHG TC SARGUJA BARIYON(19:15:01)",
    videoName: "SHG TC SARGUJA BARIYON(19:15:01) - 2025/09/19 16:53 GMT+05:30 – Recording 2",
    videoUrl: "https://drive.google.com/file/d/1hlEkqgTo-cj__3jK1onXhlNxRkemQ3-f/view",
    dateCreated: "2025-09-19",
    output: "",
    engagement: 18,
    engagementComments: "",
    classIssues: 14,
    classIssuesComments: "",
    instructorIssues: 15,
    instructorIssuesComments: "",
    contentStructure: 18,
    contentStructureComments: "",
    platformUsage: 19,
    platformUsageComments: "",
    finalScore: 84,
    issuesToImprove: "Strategies for managing classroom noise needed"
  },
  {
    srNo: 33,
    shgName: "SHG TC MIRZAPUR PURZAGIR(02:19:01)",
    videoName: "SHG TC MIRZAPUR PURZAGIR(02:19:01) - 2025/09/19 16:08 GMT+05:30 – Recording",
    videoUrl: "https://drive.google.com/file/d/1V07RKQVDyn03j5Vek1qn_lvUMyXpv7Kb/view",
    dateCreated: "2025-09-19",
    output: "",
    engagement: 18,
    engagementComments: "",
    classIssues: 16,
    classIssuesComments: "",
    instructorIssues: 19,
    instructorIssuesComments: "",
    contentStructure: 20,
    contentStructureComments: "",
    platformUsage: 20,
    platformUsageComments: "",
    finalScore: 93,
    issuesToImprove: "significant background noise was present"
  },
  {
    srNo: 34,
    shgName: "SHG TC TIKAMGARH BIRDHA(23:21:02)",
    videoName: "SHG TC TIKAMGARH BIRDHA(23:21:02) - 2025/09/19 16:05 GMT+05:30 – Recording",
    videoUrl: "NA",
    dateCreated: "2025-09-19",
    output: "Dippty sat but No Light",
    engagement: 0,
    engagementComments: "NA",
    classIssues: 0,
    classIssuesComments: "NA",
    instructorIssues: 10,
    instructorIssuesComments: "No instructor-related issues were noted during the session.The instructor was professionally-dressed",
    contentStructure: 0,
    contentStructureComments: "NA",
    platformUsage: 5,
    platformUsageComments: "Optimal use of screen sharing, prepared PDFs for visual session.",
    finalScore: 15,
    issuesToImprove: ""
  },
  {
    srNo: 35,
    shgName: "SHG TC BUXAR ITARAHI(06:10:02)",
    videoName: "SHG TC BUXAR ITARAHI(06:10:02)  - 2025/09/23 05:54 GMT+05:30 – Recording",
    videoUrl: "https://drive.google.com/file/d/19RiHiN55oCD6nLnkfVvONkzetTst1_AM/view",
    dateCreated: "2025-09-23",
    output: "",
    engagement: 18,
    engagementComments: "",
    classIssues: 15,
    classIssuesComments: "",
    instructorIssues: 18,
    instructorIssuesComments: "",
    contentStructure: 18,
    contentStructureComments: "",
    platformUsage: 18,
    platformUsageComments: "",
    finalScore: 85,
    issuesToImprove: "The classroom's lighting was poor"
  },
  {
    srNo: 36,
    shgName: "SHG TC MUZAFFARPUR BHUSRA(21:15:02)",
    videoName: "SHG TC MUZAFFARPUR BHUSRA(21:15:02) - 2025/09/23 06:31 GMT+05:30 – Recording",
    videoUrl: "https://drive.google.com/file/d/14ep1cV9ddbQRweR4pfwHgyPhznSCEYQp/view",
    dateCreated: "2025-09-23",
    output: "",
    engagement: 17,
    engagementComments: "",
    classIssues: 5,
    classIssuesComments: "",
    instructorIssues: 18,
    instructorIssuesComments: "",
    contentStructure: 18,
    contentStructureComments: "",
    platformUsage: 20,
    platformUsageComments: "",
    finalScore: 78,
    issuesToImprove: "The classroom's unstable internet connection is a fatal issue that repeatedly interrupted the lesson."
  },
  {
    srNo: 37,
    shgName: "SHG TC SITAMARHI&DARBHANGA BISFI(31:07:03)",
    videoName: "SHG TC SITAMARHI&DARBHANGA BISFI(31:07:03) - 2025/09/23 16:30 GMT+05:30 – Recording 2",
    videoUrl: "https://drive.google.com/file/d/1KKv0Oi7TrSbpdpsUlwbMCl5DsNGMAdEj/view",
    dateCreated: "2025-09-23",
    output: "",
    engagement: 5,
    engagementComments: "",
    classIssues: 2,
    classIssuesComments: "",
    instructorIssues: 14,
    instructorIssuesComments: "",
    contentStructure: 16,
    contentStructureComments: "",
    platformUsage: 12,
    platformUsageComments: "",
    finalScore: 49,
    issuesToImprove: "The classroom's technical setup (audio, video, lighting) was inadequate, leading to a fatal communication breakdown. Participant interaction was mediated by a facilitator rather than being direct, indicating a disengaged or coached environment."
  },
  {
    srNo: 38,
    shgName: "SHG TC GORAKHPUR BRAMHPUR(13:05:04)",
    videoName: "SHG TC GORAKHPUR BRAMHPUR(13:05:04) - 2025/09/24 06:00 GMT+05:30 – Recording",
    videoUrl: "https://drive.google.com/file/d/1Xy7WEmlCFllyMpXKVww-s-kUOOu11N_q/view",
    dateCreated: "2025-09-24",
    output: "",
    engagement: 18,
    engagementComments: "",
    classIssues: 19,
    classIssuesComments: "",
    instructorIssues: 15,
    instructorIssuesComments: "",
    contentStructure: 19,
    contentStructureComments: "",
    platformUsage: 19,
    platformUsageComments: "",
    finalScore: 90,
    issuesToImprove: "The instructor briefly disrupted the class by disconnecting."
  },
  {
    srNo: 39,
    shgName: "SHG TC AZAMGARH BHADSAR(07:20:03)",
    videoName: "SHG TC AZAMGARH BHADSAR(07:20:03) - 2025/09/24 06:00 GMT+05:30 – Recording",
    videoUrl: "https://drive.google.com/file/d/1x5oVXL4LX4BQAHwS9mRX5LY5O8k4jxrr/view?usp=drive_link",
    dateCreated: "2025-09-24",
    output: "",
    engagement: 17,
    engagementComments: "",
    classIssues: 8,
    classIssuesComments: "",
    instructorIssues: 12,
    instructorIssuesComments: "",
    contentStructure: 18,
    contentStructureComments: "",
    platformUsage: 18,
    platformUsageComments: "",
    finalScore: 73,
    issuesToImprove: "Video lighting was poor. An initial audio echo from the classroom required the instructor to pause and ask for it to be muted"
  },
  {
    srNo: 40,
    shgName: "SHG TC SAMASTIPUR BIDUPUR(35:18:02)",
    videoName: "SHG TC SAMASTIPUR BIDUPUR(35:18:02) - 2025/09/24 07:02 GMT+05:30 – Recording",
    videoUrl: "https://drive.google.com/file/d/1p8BJDShrbZvkBOeoz3Jvd6rpHSqD-oa4/view",
    dateCreated: "2025-09-24",
    output: "",
    engagement: 8,
    engagementComments: "",
    classIssues: 10,
    classIssuesComments: "",
    instructorIssues: 16,
    instructorIssuesComments: "",
    contentStructure: 18,
    contentStructureComments: "",
    platformUsage: 18,
    platformUsageComments: "",
    finalScore: 70,
    issuesToImprove: "The students were highly disengaged, with some appearing sleepy and others talking amongst themselves."
  },
  {
    srNo: 41,
    shgName: "SHG TC SARGUJA BARIYON(19:15:01)",
    videoName: "SHG TC SARGUJA BARIYON(19:15:01) - 2025/09/24 17:14 GMT+05:30 – Recording",
    videoUrl: "https://drive.google.com/file/d/1iL8bCVlaWh_xbAr2ZWakG2aClJD8joPA/view",
    dateCreated: "2025-09-24",
    output: "",
    engagement: 18,
    engagementComments: "",
    classIssues: 17,
    classIssuesComments: "",
    instructorIssues: 18,
    instructorIssuesComments: "",
    contentStructure: 19,
    contentStructureComments: "",
    platformUsage: 20,
    platformUsageComments: "",
    finalScore: 92,
    issuesToImprove: "The instructor briefly disconnected twice during the session. Students tended to answer questions in chorus rather than individually."
  },
  {
    srNo: 42,
    shgName: "SHG TC MUZAFFARPUR BHUSRA(21:15:02)",
    videoName: "SHG TC MUZAFFARPUR BHUSRA(21:15:02) - 2025/09/25 06:31 GMT+05:30 – Recording",
    videoUrl: "https://drive.google.com/file/d/14ep1cV9ddbQRweR4pfwHgyPhznSCEYQp/view",
    dateCreated: "2025-09-25",
    output: "",
    engagement: 17,
    engagementComments: "Ravikesh No recording",
    classIssues: 8,
    classIssuesComments: "Ravikesh No recording",
    instructorIssues: 12,
    instructorIssuesComments: "Ravikesh No recording",
    contentStructure: 18,
    contentStructureComments: "Ravikesh No recording",
    platformUsage: 18,
    platformUsageComments: "",
    finalScore: 73,
    issuesToImprove: ""
  }
];